<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=yes, initial-scale=0.3, maximum-scale=1, minimum-scale=0.1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{$title}</title>
    {include file="www/resfile/css.html" /}
    <!--if lt IE 9-->
    <script type="text/javascript" src="/www/resfile/scripts/html5.js"></script>
    <script type="text/javascript" src="/www/resfile/scripts/respond.min.js"></script>
    <!--endif-->
    {include file="www/resfile/js.html" /}
</head>
<body>
{__CONTENT__}
</body>
</html>