{layout name="../../view/shared/manage" /}
<style>
    @import "/www/resfile/css/site.css";

    .top {
        font-weight: bold;
        font-size: 16px;
        border-bottom: 1px solid #aaaaaa;
        display: flex;
        flex-flow: row;
        justify-content: flex-start;
    }

    .top .active {
        padding: 8px;
        background-color: #000000;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #FFFFFF;
    }

    .top a {
        padding: 8px;
        background-color: #aaaaaa;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #000;
        text-decoration: none;
    }

    .top a:hover {
        background-color: #7a7a7a;
    }

    .box ul,
    .box li {
        list-style: none;
    }

    .box {
        margin-top: 10px;
    }

    .box li {
        padding: 10px 5px;
    }
</style>
<div class="top">
    <a href="/home/manage/download" class="active">下载添加</a>
    <a href="/home/manage/download_edit">下载管理</a>
</div>
<div class="box">
    <form id="form1">
        <ul>
            <li>
                <input name="title" type="text" class="form-control" placeholder="请输入标题">
            </li>
            <li>
                <ul style="display: flex; flex-flow: row;">
                    <li style="line-height: 32px; min-width: 80px;">绑定产品:</li>
                    <li>
                        <select class="form-control" name="t1">
                            <option value="0" selected>请选择...</option>
                            <option value="1">键盘</option>
                            <option value="2">键帽</option>
                            <option value="3">鼠标垫</option>
                        </select>
                    </li>
                    <li>
                        <select class="form-control" name="t2"></select>
                    </li>
                </ul>
            </li>
            <li>
                <span style="color: #ff0000;">注意：附件上传最大（50mb)</span>
            </li>
            <li>
                <input type="file" name="file" style="width: 50%;">
            </li>
            <li>
                    <textarea class="form-control" name="contentval" id="contentval"
                              style="resize: none; min-height:330px;"></textarea>
            </li>
            <li>
                <button type="button" name="submit" style="width: 100%; padding: 10px" class="btn btn-primary"><i
                            class="fa fa-upload" style="margin-right: 8px;"></i>添加
                </button>
                <button type="button" name="subnew" class="btn btn-danger hidden"
                        style="width: 100%; padding-top: 12px; padding-bottom: 12px;margin-top: 15px;"><i
                            class="fa fa-plus"
                            style="margin-right: 8px;"></i>继续添加
                </button>
            </li>
        </ul>
    </form>
</div>

<script type="text/javascript">
    $('#form1 button[name="subnew"]').click(function () {
        window.location.href = '/home/manage/download.html';
    });

    $('#form1 button[name="submit"]').click(function () {
        if ($(this).hasClass('disabled')) {
            return false;
        }

        var title = $('#form1 input[name="title"]').val();
        if (title == '') {
            xtip.alert('请输入标题！', 'e');
            return false;
        }

        var val = $('#form1 textarea[name="contentval"]').val();
        if (val == '') {
            xtip.alert('请输入简介内容！', 'e');
            return false;
        }

        var btn = $(this);
        var btnnew = $('#form1 button[name="subnew"]');
        var $i = $(this).parent().find('i');

        $(btn).addClass('disabled');
        $($i).addClass('fa-circle-o-notch');
        $($i).addClass('fa-spin');
        $($i).removeClass('fa-edit');

        var f = $('#form1');
        f.ajaxSubmit({
            url: '/home/handles/add_download.html?x=' + Math.random(),
            type: 'post',
            success: function (d) {
                switch (d.t) {
                    case 'suc':
                        xtip.alert(d.m, 's');
                        $($i).removeClass('fa-spin');
                        $($i).removeClass('fa-circle-o-notch');
                        $($i).addClass('fa-edit');
                        $(btnnew).removeClass('hidden');
                        break;
                    case 'err':
                        xtip.alert(d.m, 'e');
                        $($i).removeClass('fa-spin');
                        $($i).removeClass('fa-circle-o-notch');
                        $($i).addClass('fa-edit');
                        $(btn).removeClass('disabled');
                        break;
                }
            }
        })
    });

    $('#form1 select[name="t1"]').change(function () {
        var id = $(this).val();
        if (id == 0) {
            return false;
        }

        var $dom = $('#form1 select[name="t2"]');
        $($dom).html('');

        $.ajax({
            url: '/home/handles/gettype.html?x=' + Math.random(),
            type: 'post',
            data: {id: id},
            success: function (d) {
                if (d.t == 'suc') {
                    var arr = d.m.split('<bbt>');
                    var xhtml;
                    $(arr).each(function (index, val) {
                        var narr = val.split('<kpt>');
                        var nid = narr[1];
                        var nval = narr[0];
                        xhtml += '<option value="' + nid + '">' + nval + '</option>';
                    });
                    $($dom).html(xhtml);
                }
            }
        })
    });
</script>