{layout name="../../view/shared/manage" /}
<style>
    @import "/www/resfile/css/site.css";
    @import "/www/resfile/scripts/xeditor/css/xeditor.css";

    .top {
        font-weight: bold;
        font-size: 16px;
        border-bottom: 1px solid #aaaaaa;
        display: flex;
        flex-flow: row;
        justify-content: flex-start;
    }

    .top span {
        padding: 8px;
        background-color: #aaaaaa;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #000;
    }

    .top .active {
        padding: 8px;
        background-color: #000000;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #FFFFFF;
    }

    .top a {
        padding: 8px;
        background-color: #aaaaaa;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #000;
        text-decoration: none;
    }

    .top a:hover {
        background-color: #7a7a7a;
    }

    .can-edit {
        margin-top: 10px;
    }

    .can-edit ul,
    .can-edit li {
        list-style: none;
    }

    .btn {
        padding: 6px 30px;
    }


</style>
<script type="text/javascript" src="/www/resfile/scripts/xeditor/js/xeditor.js"></script>
<div class="top">
    <a href="/home/manage/newgoods.html">新品发布</a>
    <a href="/home/manage/newgoodsedit.html">新品发布管理</a>
</div>
<div class="can-edit">
    <form id="form1" class="form1">
        <ul>
            <li style="margin-bottom: 10px;">
                <input class="form-control" name="title" type="text" placeholder="请输入标题"
                       value="<?php echo $db['title'] ?>">
                <input type="hidden" name="id" value="<?php echo $id ?>">
            </li>
            <li>
                <textarea class="form-control" name="contentval" id="contentval"
                          style="resize: none; min-height: 700px;">{$db['content']}</textarea>
            </li>
            <li style="margin-top: 10px; margin-bottom: 20px;">
                <button type="button" name="but" class="btn btn-warning"><i class="fa fa-edit"
                                                                            style="margin-right: 5px;"></i>修改
                </button>
            </li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    insert_editor('contentval');

    $('#form1 button[name="but"]').click(function () {
        if ($(this).hasClass('disabled')) {
            return false;
        }

        var val = $('#form1 textarea[name="contentval"]').val();
        var title = $('#form1 input[name="title"]').val();
        var id = $('#form1 input[name="id"]').val();

        if (title == '') {
            xtip.alert('标题不能为空！', 'e');
            return false;
        }
        if (val == '') {
            xtip.alert('内容不能为空！', 'e');
            return false;
        }

        var dom = this;
        var dom_i = $(this).find('i');

        $(dom).addClass('disabled');
        $(dom_i).addClass('fa-circle-o-notch');
        $(dom_i).addClass('fa-spin');
        $(dom_i).removeClass('fa-edit');

        $.ajax({
            url: '/home/handles/edit_newgoods.html?x=' + Math.random(),
            type: 'post',
            data: {val: val, title: title, id: id},
            success: function (data) {
                $(dom_i).removeClass('fa-spin');
                $(dom_i).removeClass('fa-circle-o-notch');
                $(dom_i).addClass('fa-edit');
                $(dom).removeClass('disabled');
                switch (data.t) {
                    case 'suc':
                        xtip.alert(data.m, 's');
                        break;
                    case 'err':
                        xtip.alert(data.m, 'e');
                        break;
                }
            }
        });

    })
</script>