{layout name="../../view/shared/manage" /}
<?php
?>
<style>
    @import "/www/resfile/css/site.css";
    @import "/www/resfile/scripts/xeditor/css/xeditor.css";

    .top {
        font-weight: bold;
        font-size: 16px;
        border-bottom: 1px solid #aaaaaa;
        display: flex;
        flex-flow: row;
        justify-content: flex-start;
    }

    .top span {
        padding: 8px;
        background-color: #aaaaaa;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #000;
    }

    .top .active {
        padding: 8px;
        background-color: #000000;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #FFFFFF;
    }

    .top a {
        padding: 8px;
        background-color: #aaaaaa;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #000;
        text-decoration: none;
    }

    .top a:hover {
        background-color: #7a7a7a;
    }

    .can-edit {
        margin-top: 10px;
    }

    .can-edit ul,
    .can-edit li {
        list-style: none;
    }

    .btn {
        padding: 6px 30px;
    }

    .box {
        margin-top: 10px;
        border-top: 1px solid #ffb990;
    }

    .box ul,
    .box li {
        list-style: none;
    }

    .box ul {
        width: 100%;
        border-bottom: 1px solid #ffb990;
        cursor: pointer;
        overflow: hidden;
    }

    .box ul:hover {
        background-color: #fff1e9;
    }

    .box li {
        padding: 5px 10px;
        float: left;
    }

    .box a {
        display: block;
        padding: 0px 8px;
        text-decoration: none;
        background-color: #d20000;
        color: #FFFFFF;
        border-radius: 3px;
        float: left;
        margin-left: 8px;
    }

    .box a:hover {
        background-color: #7d0000;
    }

    .box i {
        margin-right: 8px;
    }


</style>
<script type="text/javascript" src="/www/resfile/scripts/xeditor/js/xeditor.js"></script>
<div class="top">
    <a href="/home/manage/newgoods.html">新品发布</a>
    <span class="active">新品发布管理</span>
</div>
<div class="box">
    <?php
    foreach ($db_xnewgoods as $db) {
        echo '<ul>';
        echo '<li style="background-color: #ffd9c3;">' . date('Y-m-d', strtotime($db['time'])) . '</li>';
        echo '<li>' . $db['title'] . '</li>';
        echo '<li style="float: right;">';
        echo '<a name="btn_edit" v="' . $db['id'] . '"><i class="fa fa-edit">修改</i></a>';
        echo '<a name="btn_del" v="' . $db['id'] . '"><i class="fa fa-trash-o"></i>删除</a>';
        echo '</li>';
        echo '</ul>';
    }
    ?>
</div>
<div class="page">
    {$db_xnewgoods->render()}
</div>

<script type="text/javascript">
    $('.box a[name="btn_edit"]').click(function () {
        var id = $(this).attr('v');
        window.location.href = '/home/manage/newgoods_e.html?id=' + id + '&x=' + Math.random();
    });

    $('.box a[name="btn_del"]').click(function () {
        if ($(this).hasClass('disabled')) {
            return false;
        }
        var thebtn = this;
        var thedom = $(this).parent().parent();
        var id = $(this).attr('v');
        var html = $(this).html();
        xtip.confirm('确认删除吗？', function () {
            $(thebtn).addClass('disabled');
            $(thebtn).html('<i class="fa fa-spin fa-circle-o-notch"></i>稍候');
            $.ajax({
                url: '/home/handles/del_newgoods?x=' + Math.random(),
                type: 'post',
                data: {id: id},
                success: function (d) {
                    $(thebtn).html(html);
                    $(thebtn).removeClass('disabled');
                    switch (d.t) {
                        case 'suc':
                            xtip.alert(d.m, 's');
                            $(thedom).remove();
                            break;
                        case 'err':
                            xtip.alert(d.m, 'e');
                            break;
                    }
                }
            })
        });
    });
</script>