{layout name="../../view/shared/manage" /}
<style>
    @import "/www/resfile/css/site.css";
    @import "/www/resfile/scripts/xeditor/css/xeditor.css";

    .top {
        font-weight: bold;
        font-size: 16px;
        border-bottom: 1px solid #aaaaaa;
        display: flex;
        flex-flow: row;
        justify-content: flex-start;
    }

    .top .active {
        padding: 8px;
        background-color: #000000;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #FFFFFF;
    }

    .top a {
        padding: 8px;
        background-color: #aaaaaa;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #000;
        text-decoration: none;
    }

    .top a:hover {
        background-color: #7a7a7a;
    }

    .content ul,
    .content li {
        list-style: none;
    }

    .content {
        margin-top: 20px;
        padding-right: 300px;
        position: relative;
    }

    .content .imgbtn {
        display: flex;
        justify-content: flex-start;
        margin: 10px 0 10px 0;
    }

    .content .imgbtn a {
        background-color: #00a80e;
        color: #000;
        display: block;
        border-radius: 3px;
        text-decoration: none;
        padding: 5px 10px;
        color: #FFFFFF;
        margin-right: 10px;
        cursor: pointer;
    }

    .content .imgbtn a:hover {
        background-color: #005b08;

    }

    .content .viewimg ul, {
        list-style: none;
    }

    .content .viewimg {
        position: absolute;
        z-index: 9;
        right: 10px;
        /*background-color: #d9534f;*/
        display: flex;
        flex-flow: column;
    }

    .content .viewimg img {
        max-width: 270px;
    }

    .content .a2 span {
        padding: 8px 5px;
        width: 100px;
    }
</style>
<script type="text/javascript" src="/www/resfile/scripts/xeditor/js/xeditor.js"></script>
<div class="top">
    <a href="/home/manage/goods" class="active">产品添加</a>
    <a href="/home/manage/products_edit">产品管理</a>
</div>
<div class="content">
    <form id="form1" name="form1" method="post">
        <ul>
            <li>
                <input class="form-control" type="text" name="title" placeholder="商品名称"
                       value="<?php echo $db['title'] ?>">
                <input type="hidden" name="id" value="<?php echo $id ?>">
            </li>
            <li style="margin-top: 10px;padding: 8px; 5px;background-color: #b9ff99; color: #2c6a0f; border:1px solid #3a8e13; font-weight: bold; font-size: 16px;">
                产品介绍
            </li>
            <li style="margin-top: 10px;">
                <textarea class="form-control" name="contentval" id="contentval"
                          style="resize: none; min-height:630px;"><?php echo $db['val'] ?></textarea>
            </li>
            <li style="margin-top: 20px; margin-bottom: 20px;">
                <button type="button" name="submit" class="btn btn-success"
                        style="width: 100%; padding-top: 12px; padding-bottom: 12px;"><i class="fa fa-edit"
                                                                                         style="margin-right: 8px;"></i>修改
                </button>
            </li>
        </ul>
    </form>
</div>

<script type="text/javascript">
    insert_editor('contentval');

    $('.content #form1 button[name="submit"]').click(function () {
        var $but = $(this);
        var $i = $(this).parent().find('i');
        if ($(this).hasClass('disabled')) {
            return false;
        }
        var title = $('#form1 input[name="title"]').val();
        if (title == '') {
            xtip.alert('请输入商品标题！', 'e');
            return false;
        }

        var f = $('#form1');
        $($but).addClass('disabled');

        $($i).addClass('fa-circle-o-notch');
        $($i).addClass('fa-spin');
        $($i).removeClass('fa-edit');

        f.ajaxSubmit({
            url: '/home/handles/edit_products.html?x=' + Math.random(),
            type: 'post',
            success: function (d) {
                switch (d.t) {
                    case 'suc':
                        xtip.alert(d.m, 's');
                        $($i).removeClass('fa-spin');
                        $($i).removeClass('fa-circle-o-notch');
                        $($i).addClass('fa-edit');
                        $($butnew).removeClass('hidden');
                        break;
                    case 'err':
                        xtip.alert(d.m, 'e');
                        $($i).removeClass('fa-spin');
                        $($i).removeClass('fa-circle-o-notch');
                        $($i).addClass('fa-edit');
                        $($but).removeClass('disabled');
                        break;
                }
            }
        });

    });
</script>