{layout name="../../view/shared/manage" /}
<style>
    @import "/www/resfile/css/site.css";

    ul, li {
        list-style: none;
    }

    .top {
        font-weight: bold;
        font-size: 16px;
        border-bottom: 1px solid #aaaaaa;
        display: flex;
        flex-flow: row;
        justify-content: flex-start;
    }

    .top .active {
        padding: 8px;
        background-color: #000000;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #FFFFFF;
    }

    .top a {
        padding: 8px;
        background-color: #aaaaaa;
        border-radius: 5px 5px 0 0;
        border-bottom: 3px solid #000;
        display: block;
        color: #000;
        text-decoration: none;
    }

    .top a:hover {
        background-color: #7a7a7a;
    }

    .page {
        padding: 30px;
    }

    .page li {
        padding-bottom: 10px;
    }
</style>
<div class="page">
    <form id="form1">
        <ul style="width: 360px;">
            <li>
                <input class="form-control" type="password" name="pwd1" placeholder="请输入原密码">
            </li>
            <li style="margin-top: 50px;">
                <input class="form-control" type="password" name="pwd2" placeholder="请输入新密码">
            </li>
            <li>
                <input class="form-control" type="password" name="pwd3" placeholder="请再次输入新密码">
            </li>
            <li>
                <button class="btn btn-success" type="button" name="sub" style="width: 200px; margin-top: 30px;"><i
                            class="fa fa-upload"
                            style="margin-right: 5px;"></i>修改密码
                </button>
            </li>

        </ul>
    </form>
</div>

<script>
    $('#form1 button[name="sub"]').click(function () {
        var f = $('#form1');

        f.ajaxSubmit({
            url: '/home/handles/edit_pwd',
            type: 'post',
            success: function (d) {
                switch (d.t) {
                    case 'suc':
                        xtip.alert(d.m, 's');
                        break;
                    case 'err':
                        xtip.alert(d.m, 'e');
                        break;
                }
            }
        })
    });
</script>