{layout name="../../view/shared/home" /}
<style>
    @import "/www/resfile/css/site.css";

    ul, li {
        list-style: none;
    }

    list .xbox {
        width: 25%;
        margin: 5px;
        background: #000;
    }

    list .xrow {
        display: flex;
        flex-flow: row;
        flex-wrap: nowrap;
        justify-content: space-between;
    }

    list img {
        width: 100%;
    }

    list .main {
        margin: 50px 0;
    }

    list .xurl {
        text-decoration: none;
        cursor: pointer;
        color: #666;
        border: 1px solid #2d2d2d;
        display: block;
        padding: 15px;
        height: 100%;
    }

    list .xurl:hover {
        border: 1px solid #790000;
    }

    list .xtitle {
        text-align: center;
    }

    list .page {
        display: flex;
        flex-flow: row;
        justify-content: flex-end;
    }

    .pagination li a,
    .pagination li span {
        position: relative;
        float: left;
        padding: 3px 10px;
        margin-left: -1px;
        line-height: 1.42857143;
        text-decoration: none;
        background-color: #101010;
        border: 1px solid #2d2d2d;
        border-radius: 0;
        color: #a4a4a4;
    }

    .pagination .active a,
    .pagination .active span,
    .pagination .active a:hover,
    .pagination .active a:focus,
    .pagination .active span:hover,
    .pagination .active span:focus {
        z-index: 2;
        color: #fff;
        background-color: #8a8b88;
        border-color: #878682;
    }

    .pagination li a:hover {
        border-color: #40403e;
        background-color: #676864;
        color: #000;
    }

    .pagination li a:focus {
        color: #000;
    }

    .pagination li:first-child a, .pagination li:first-child span {
        border-radius: 0;
    }

    .pagination li:last-child a, .pagination li:last-child span {
        border-radius: 0;
    }

    .pagination > .disabled > span,
    .pagination > .disabled > span:hover,
    .pagination > .disabled > span:focus,
    .pagination > .disabled > a,
    .pagination > .disabled > a:hover,
    .pagination > .disabled > a:focus {
        color: #777;
        cursor: not-allowed;
        background-color: #444444;
        border-color: #5e5e5e;
    }

    .menu {
        padding-top: 50px;
        text-align: center;
    }

    .download-lists li {
        vertical-align: top;
        transition: all .3s ease 0s;
        cursor: pointer;
        text-align: center;
        padding-bottom: 1%;
        width: 9.64%;
        display: inline-block;
        margin-bottom: .5%;
        background: #000;
        height: 100px;
        text-transform: uppercase;
        padding-top: 10px;
        line-height: 16px;
    }

    .download-lists li span {
        width: 50px;
        height: 50px;
        background: url("/www/image/list-icons.png") no-repeat;
        display: inline-block;
    }

    .download-lists li:hover {
        background: #222;
    }

    .download-lists a {
        color: #aaaaaa;
        text-decoration: none;
    }
</style>
<section id="inner-headline">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="pageTitle">
                    <?php
                    switch ($id) {
                        case '1':
                            echo '机械键盘';
                            break;
                        case '2':
                            echo '键盘帽';
                            break;
                        case '3':
                            echo '周边产品';
                            break;
                    }
                    ?>
                </h2>
            </div>
        </div>
    </div>
</section>

<list>
    <div class="container">
        <div class="menu">
            <div class="download-lists">
                <ul><a href="/home/main/download.html?id=1">
                        <li id="one1">
                            <span class="download01" style="background-position: 0px 0;"></span>
                            <p>机械键盘</p>
                        </li>
                    </a>
                    <a href="/home/main/download.html?id=2">
                        <li id="one2">
                            <span class="download02" style="background-position: -605px 0;"></span>
                            <p>键盘帽</p>
                        </li>
                    </a>
                    <a href="/home/main/download.html?id=3">
                        <li id="one3">
                            <span class="download03" style="background-position: -365px 0;"></span>
                            <p>周边产品</p>
                        </li>
                    </a>
                </ul>
            </div>
        </div>
        <div class="main">
            <?php
            if (count($db) < 1) {
                echo '<div style="display: flex; justify-content: center;">抱歉，此类别中还没有产品。</div>';
            }
            ?>
            <div class="xrow">
                <?php
                for ($i = 0; $i < count($db); $i++) {
                    $mod = $i + 1;
                    echo '<div class="xbox">';
                    echo '<a class="xurl" v="' . $db[$i]['id'] . '">';
                    echo '<ul>';
                    echo '<li class="ximg"><img src="/www/upload/goods/' . $imgarr[$i] . '"></li>';
                    echo '<li class="xtitle h4">' . $db[$i]['title'] . '</li>';
                    echo '</ul></a>';
                    echo '</div>';
                    if ($mod % 4 == 0) {
                        echo '</div><div class="xrow">';
                    }
                }
                ?>
            </div>
            <div class="page">
                <?php echo $db->render(); ?>
            </div>
        </div>
    </div>
</list>

<script type="text/javascript">
    $('a.xurl').click(function () {
        var id = $(this).attr('v');

        layer.open({
            type: 2,
            title: '',
            shadeClose: true,
            shade: 0.8,
            area: ['560px', '460px'],
            content: '/home/main/down.html?id=' + id
        });
    })
</script>
